apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bai-zhan-ingress
  namespace: bai-zhan
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: api.bai-zhan.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bai-zhan-web
                port:
                  number: 80
