apiVersion: v1
kind: Service
metadata:
  name: bai-zhan-web
  namespace: bai-zhan
spec:
  selector:
    app: bai-zhan-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
